### ISSUE TITLE
Stoping the Battle (React JS)

### ISSUE THREAD

**Issue by Harkindey** [Harkindey/Github-Battles#1]
When the accounts are of same username, the system still chooses a winner which it isn't suppose to. 
<img width="1228" alt="screen shot 2017-10-15 at 12 10 14 am" src="https://user-images.githubusercontent.com/14913673/31580065-44533bbe-b13d-11e7-8ef3-cf1eadf13988.png">

so the action to battle should either be disabled if the username is same or an alert is thrown to tell the user the right thing to do, OR ANY OTHER WAY , This is pretty easy dropping in on hacktoberfest.
<img width="1153" alt="screen shot 2017-10-15 at 12 13 18 am" src="https://user-images.githubusercontent.com/14913673/31580082-b12019ec-b13d-11e7-8f38-3c58f6f97e06.png">

**Comment by nacq** [comment]
I'll check this out!

**Comment by Harkindey** [comment]
@nicolasacquaviva :smile: Thanks

**Comment by Harkindey** [comment]
@nicolasacquaviva Thanks #Deployed you can check it [GitHub Battles!](https://github-battle-ea613.firebaseapp.com/)
