### ISSUE TITLE
Wrong Result (React Js)

### ISSUE THREAD

**Issue by Harkindey** [Harkindey/Github-Battles#3]
For users with same score it still chooses a winner, and a loser , there should be a draw option
<img width="1280" alt="screen shot 2017-10-16 at 7 31 05 am" src="https://user-images.githubusercontent.com/14913673/31598201-4084074a-b244-11e7-9a55-9b7d01bfa07b.png">

**Comment by MelisaIm** [comment]
Could I work on this?

**Comment by Harkindey** [comment]
@Melisalm it has been fixed ma'am, Thanks.
